version: 0.2
env:
  secrets-manager:
    GOOGLE_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:GOOGLE_API_KEY"
    OPENAI_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:OPENAI_API_KEY"
    ANTHROPIC_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:ANTHROPIC_API_KEY"
    MISTRAL_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:MISTRAL_API_KEY"
    COHERE_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:COHERE_API_KEY"
    GROQ_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:GROQ_API_KEY"
    MARITACA_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:MARITACA_API_KEY"
    SAMBANOVA_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:SAMBANOVA_API_KEY"
  variables:
    CODEARTIFACT_URL: "https://repense-329495585553.d.codeartifact.us-east-2.amazonaws.com/pypi/repense-ai/"
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - python -m pip install --upgrade pip
      - pip install poetry
      - python -m poetry install
      - poetry config virtualenvs.create false
  pre_build:
    commands:
      - echo "Running tests..."
      - python -m pytest
  build:
    commands:
      - python -m poetry build
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain repense --domain-owner 329495585553 --query authorizationToken --output text)
      - python -m poetry config pypi-token.repense-ai $CODEARTIFACT_AUTH_TOKEN
      - python -m poetry config repositories.repense-ai $CODEARTIFACT_URL
      - python -m poetry publish -r repense-ai
artifacts:
  files: dist/*
