version: 0.2

env:
  secrets-manager:
    GOOGLE_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:GOOGLE_API_KEY"
    OPENAI_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:OPENAI_API_KEY"
    ANTHROPIC_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:ANTHROPIC_API_KEY"
    MISTRAL_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:MISTRAL_API_KEY"
    COHERE_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:COHERE_API_KEY"
    GROQ_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:GROQ_API_KEY"
    MARITACA_API_KEY: "arn:aws:secretsmanager:us-east-2:329495585553:secret:genai-9vocOE:MARITACA_API_KEY"

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - python -m pip install --upgrade pip
      - pip install poetry
      - python -m poetry install

  pre_build:
    commands:
      - echo "Running tests..."
      - source $(poetry env info --path)/bin/activate
      - python -m pytest

  build:
    commands:
      - source $(poetry env info --path)/bin/activate
      - python -m poetry build
      - python -m poetry config repositories.repense-ai $CODEARTIFACT_URL
      - python -m poetry publish -r repense-ai

artifacts:
  files: dist/*
